import 'package:flutter/material.dart';
import 'package:aedify/app/theme/app_colors.dart';
import 'package:aedify/shared/theme/app_spacing.dart';
import 'package:aedify/shared/theme/app_text_styles.dart';

class AppTheme {
  AppTheme._();

  static final lightTheme = ThemeData(
    useMaterial3: true,
    brightness: Brightness.light,
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: AedifyLightColors.primary,
      onPrimary: AedifyLightColors.onPrimary,
      primaryContainer: AedifyLightColors.primaryContainer,
      onPrimaryContainer: AedifyLightColors.onPrimaryContainer,
      primaryFixed: AedifyLightColors.primaryFixed,
      primaryFixedDim: AedifyLightColors.primaryFixedDim,
      onPrimaryFixed: AedifyLightColors.onPrimaryFixed,
      onPrimaryFixedVariant: AedifyLightColors.onPrimaryFixedVariant,
      secondary: AedifyLightColors.secondary,
      onSecondary: AedifyLightColors.onSecondary,
      secondaryContainer: AedifyLightColors.secondaryContainer,
      onSecondaryContainer: AedifyLightColors.onSecondaryContainer,
      secondaryFixed: AedifyLightColors.secondaryFixed,
      secondaryFixedDim: AedifyLightColors.secondaryFixedDim,
      onSecondaryFixed: AedifyLightColors.onSecondaryFixed,
      onSecondaryFixedVariant: AedifyLightColors.onSecondaryFixedVariant,
      tertiary: AedifyLightColors.tertiary,
      onTertiary: AedifyLightColors.onTertiary,
      tertiaryContainer: AedifyLightColors.tertiaryContainer,
      onTertiaryContainer: AedifyLightColors.onTertiaryContainer,
      tertiaryFixed: AedifyLightColors.tertiaryFixed,
      tertiaryFixedDim: AedifyLightColors.tertiaryFixedDim,
      onTertiaryFixed: AedifyLightColors.onTertiaryFixed,
      onTertiaryFixedVariant: AedifyLightColors.onTertiaryFixedVariant,
      error: AedifyLightColors.error,
      onError: AedifyLightColors.onError,
      errorContainer: AedifyLightColors.errorContainer,
      onErrorContainer: AedifyLightColors.onErrorContainer,
      surface: AedifyLightColors.surface,
      onSurface: AedifyLightColors.onSurface,
      surfaceDim: AedifyLightColors.surfaceDim,
      surfaceBright: AedifyLightColors.surfaceBright,
      surfaceContainerLowest: AedifyLightColors.surfaceContainerLowest,
      surfaceContainerLow: AedifyLightColors.surfaceContainerLow,
      surfaceContainer: AedifyLightColors.surfaceContainer,
      surfaceContainerHigh: AedifyLightColors.surfaceContainerHigh,
      surfaceContainerHighest: AedifyLightColors.surfaceContainerHighest,
      onSurfaceVariant: AedifyLightColors.onSurfaceVariant,
      outline: AedifyLightColors.outline,
      outlineVariant: AedifyLightColors.outlineVariant,
      shadow: AedifyLightColors.shadow,
      scrim: AedifyLightColors.scrim,
      inverseSurface: AedifyLightColors.inverseSurface,
      onInverseSurface: AedifyLightColors.inverseOnSurface,
      inversePrimary: AedifyLightColors.inversePrimary,
      surfaceTint: AedifyLightColors.surfaceTint,
    ),
    scaffoldBackgroundColor: AedifyLightColors.surface,
    appBarTheme: const AppBarTheme(
      centerTitle: false,
      elevation: 0,
      scrolledUnderElevation: 0,
    ),
    cardTheme: CardThemeData(
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppRadius.lg),
      ),
      color: AedifyLightColors.surfaceContainerLowest,
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppRadius.full),
        ),
        padding: const EdgeInsets.symmetric(
          horizontal: AppSpacing.lg,
          vertical: AppSpacing.buttonVertical,
        ),
        textStyle: AppTextStyles.labelMd,
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: AedifyLightColors.surfaceContainerLow,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppRadius.defaultRadius),
        borderSide: BorderSide.none,
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppRadius.defaultRadius),
        borderSide: BorderSide(color: AedifyLightColors.secondary),
      ),
      contentPadding: const EdgeInsets.symmetric(
        horizontal: AppSpacing.md,
        vertical: AppSpacing.inputVertical,
      ),
    ),
    chipTheme: ChipThemeData(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppRadius.full),
      ),
      labelStyle: AppTextStyles.labelSm,
    ),
    textTheme: const TextTheme(
      displayLarge: AppTextStyles.headlineXl,
      headlineLarge: AppTextStyles.headlineLg,
      headlineMedium: AppTextStyles.headlineMd,
      headlineSmall: AppTextStyles.headlineLgMobile,
      bodyLarge: AppTextStyles.bodyLg,
      bodyMedium: AppTextStyles.bodyMd,
      labelLarge: AppTextStyles.labelMd,
      labelSmall: AppTextStyles.labelSm,
    ),
  );

  static final darkTheme = ThemeData(
    useMaterial3: true,
    brightness: Brightness.dark,
    colorScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: AedifyDarkColors.primary,
      onPrimary: AedifyDarkColors.onPrimary,
      primaryContainer: AedifyDarkColors.primaryContainer,
      onPrimaryContainer: AedifyDarkColors.onPrimaryContainer,
      primaryFixed: AedifyDarkColors.primaryFixed,
      primaryFixedDim: AedifyDarkColors.primaryFixedDim,
      onPrimaryFixed: AedifyDarkColors.onPrimaryFixed,
      onPrimaryFixedVariant: AedifyDarkColors.onPrimaryFixedVariant,
      secondary: AedifyDarkColors.secondary,
      onSecondary: AedifyDarkColors.onSecondary,
      secondaryContainer: AedifyDarkColors.secondaryContainer,
      onSecondaryContainer: AedifyDarkColors.onSecondaryContainer,
      secondaryFixed: AedifyDarkColors.secondaryFixed,
      secondaryFixedDim: AedifyDarkColors.secondaryFixedDim,
      onSecondaryFixed: AedifyDarkColors.onSecondaryFixed,
      onSecondaryFixedVariant: AedifyDarkColors.onSecondaryFixedVariant,
      tertiary: AedifyDarkColors.tertiary,
      onTertiary: AedifyDarkColors.onTertiary,
      tertiaryContainer: AedifyDarkColors.tertiaryContainer,
      onTertiaryContainer: AedifyDarkColors.onTertiaryContainer,
      tertiaryFixed: AedifyDarkColors.tertiaryFixed,
      tertiaryFixedDim: AedifyDarkColors.tertiaryFixedDim,
      onTertiaryFixed: AedifyDarkColors.onTertiaryFixed,
      onTertiaryFixedVariant: AedifyDarkColors.onTertiaryFixedVariant,
      error: AedifyDarkColors.error,
      onError: AedifyDarkColors.onError,
      errorContainer: AedifyDarkColors.errorContainer,
      onErrorContainer: AedifyDarkColors.onErrorContainer,
      surface: AedifyDarkColors.surface,
      onSurface: AedifyDarkColors.onSurface,
      surfaceDim: AedifyDarkColors.surfaceDim,
      surfaceBright: AedifyDarkColors.surfaceBright,
      surfaceContainerLowest: AedifyDarkColors.surfaceContainerLowest,
      surfaceContainerLow: AedifyDarkColors.surfaceContainerLow,
      surfaceContainer: AedifyDarkColors.surfaceContainer,
      surfaceContainerHigh: AedifyDarkColors.surfaceContainerHigh,
      surfaceContainerHighest: AedifyDarkColors.surfaceContainerHighest,
      onSurfaceVariant: AedifyDarkColors.onSurfaceVariant,
      outline: AedifyDarkColors.outline,
      outlineVariant: AedifyDarkColors.outlineVariant,
      shadow: AedifyDarkColors.shadow,
      scrim: AedifyDarkColors.scrim,
      inverseSurface: AedifyDarkColors.inverseSurface,
      onInverseSurface: AedifyDarkColors.inverseOnSurface,
      inversePrimary: AedifyDarkColors.inversePrimary,
      surfaceTint: AedifyDarkColors.surfaceTint,
    ),
    scaffoldBackgroundColor: AedifyDarkColors.surface,
    appBarTheme: const AppBarTheme(
      centerTitle: false,
      elevation: 0,
      scrolledUnderElevation: 0,
    ),
    cardTheme: CardThemeData(
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppRadius.lg),
      ),
      color: AedifyDarkColors.surfaceContainer,
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(AppRadius.full),
        ),
        padding: const EdgeInsets.symmetric(
          horizontal: AppSpacing.lg,
          vertical: AppSpacing.buttonVertical,
        ),
        textStyle: AppTextStyles.labelMd,
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: AedifyDarkColors.surfaceContainerLow,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppRadius.defaultRadius),
        borderSide: BorderSide.none,
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppRadius.defaultRadius),
        borderSide: BorderSide(color: AedifyDarkColors.secondaryFixedDim),
      ),
      contentPadding: const EdgeInsets.symmetric(
        horizontal: AppSpacing.md,
        vertical: AppSpacing.inputVertical,
      ),
    ),
    chipTheme: ChipThemeData(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppRadius.full),
      ),
      labelStyle: AppTextStyles.labelSm,
    ),
    textTheme: const TextTheme(
      displayLarge: AppTextStylesDark.headlineXl,
      headlineLarge: AppTextStylesDark.headlineLg,
      headlineMedium: AppTextStylesDark.headlineMd,
      headlineSmall: AppTextStylesDark.headlineLgMobile,
      bodyLarge: AppTextStylesDark.bodyLg,
      bodyMedium: AppTextStylesDark.bodyMd,
      bodySmall: AppTextStylesDark.bodySm,
      labelLarge: AppTextStylesDark.labelMd,
      labelSmall: AppTextStylesDark.labelSm,
    ),
  );
}
